name: SpectralPowered Mixin - CI (push)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@latest
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup JDK 11
        uses: actions/setup-java@latest
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Building
        run: ./gradlew build --console=plain
